services:
  config-server:
    image: config-server
    container_name: config-server
    networks:
      - microservices-network
    ports:
      - "8888:8888"

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    networks:
      - microservices-network
    ports:
      - "8761:8761"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    networks:
    - microservices-network
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust memory usage
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - //c/workspace/microservices-example/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    container_name: logstash
    networks:
      - microservices-network
    ports:
      - "5000:5000" # Logstash input
      - "5044:5044" # Filebeat input
    volumes:
      - //c/workspace/microservices-example/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # edit to your own logstash.conf location

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    networks:
      - microservices-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.3
    container_name: filebeat
    user: root
    volumes:
      - /c/workspace/microservices-example/centralized-logs:/centralized-log:ro # Mount the centralized log directory
      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # Mount the Filebeat configuration file
    depends_on:
      - logstash
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
